development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: electroshop
  pool: 5
  username: electroshop
  password: password
  socket: /tmp/mysql.sock
  host: 127.0.0.1
  port: 3309